interface Block_Device is

   Max_Block_Size : constant := 4096;

   type Block_Size_Type is range 0 .. 4096;
   type Block_Address_Type is new Word_64;
   type Device_Size_Type is new Word_64;

   procedure Get_Parameters
     (Block_Count : out Block_Address_Type;
      Block_Size  : out Block_Size_Type);
      
   procedure Read_Blocks
     (Start   : Block_Address_Type;
      Count   : Natural;
      Blocks  : out Storage_Array);

   procedure Write_Blocks
     (Start   : Block_Address_Type;
      Count   : Natural;
      Blocks  : Storage_Array);

end Block_Device;
