interface Block_Device is

   Max_Block_Size : constant := 4096;

   type Block_Size_Type is range 0 .. Max_Block_Size;
   type Block_Address_Type is mod 2 ** 48;
   type Device_Size_Type is mod 2 ** 64;

   function Block_Count return Block_Address_Type;
   function Block_Size return Block_Size_Type;
   
   procedure Read_Block
     (Address : Block_Address_Type;
      Block   : out Storage_Array);

   procedure Write_Block
     (Address : Block_Address_Type;
      Block   : Storage_Array);

   procedure Read_Blocks
     (Start   : Block_Address_Type;
      Count   : Natural;
      Blocks  : out Storage_Array);

   procedure Write_Blocks
     (Start   : Block_Address_Type;
      Count   : Natural;
      Blocks  : Storage_Array);

end Block_Device;
