interface Exec : Launch is

   function Install 
     (Executable   : interface Stream_Reader;
      Name         : String;
      Install_Caps : Capability_Array)
     return interface Launch;
      
end Exec;
