interface Process : Segment, Server, Cap is

   function Heap_Interface return interface Heap;
   
   procedure Exit_Process
     (Exit_Status : Natural);
     
   procedure Publish_Interface
     (Interface_Cap : Capability);
     
end Process;
