interface Space_Bank is

   procedure Get_Range
     (Base_Page : out Object_Id;
      Bound_Page : out Object_Id);

   procedure Get
     (Page : Object_Id;
      Data : out Storage_Array);

   procedure Put
     (Page : Object_Id;
      Data : Storage_Array);
   
   function Read return interface Stream_Reader;
   
end Space_Bank;