interface Storage is

   function Reserve_Storage
     (Size   : Word_64)
     return interface Space_Bank;
   
   procedure Add_Backing_Store
     (Store  : interface Block_Device);
     
end Storage;
